lite/Arun.cpp, lite/ana.cpp, lite/angen.cpp, lite/fn.cpp, lite/fnrun.cpp, lite/iexpr.cpp, lite/makefile, lite/nlp.cpp, lite/nlppp.cpp, lite/parse.cpp, lite/regexp.cpp, lite/str.cpp, lite/str.h, lite/thtab.h, lite/var.cpp
Incorporated Amnon's dev area fixes to the nlp-engine for linux.
=> NLP-ENGINE-005 Amnon january 2020 fixes

cs/libconsh/makefile, cs/libkbm/makefile, cs/libprim/makefile, lite/makefile, src/web/makefile, src/words/makefile
Signed-off-by: ddehilster <david@dehilster.com>
=> NLP-ENGINE-006 Makefile updates

cs/libconsh/cg.cpp, lite/dir.cpp, nlp/main.cpp, nlp/makefile
=> NLP-ENGINE-014 major overhaul of nlp.exe

cs/libkbm/con_.cpp, nlp/makefile
=> NLP-ENGINE-015 Makefile and small change print format warning

CMakeLists.txt, cs/libconsh/CMakeLists.txt, cs/libconsh/makefile, cs/libkbm/CMakeLists.txt, cs/libkbm/makefile, cs/libprim/CMakeLists.txt, cs/libprim/makefile, lite/CMakeLists.txt, lite/makefile, makeall, nlp/CMakeLists.txt, nlp/makefile
=> NLP-ENGINE-016 CMake now compiles the engine on linux

analyzers/taiparse/spec/analyzer.seq, analyzers/taiparse/spec/buff_out.pat
Signed-off-by: David de Hilster <dehilsterlexis>
=> NLP-ENGINE-023 add xml dump of final syntactic tree to file or buffer

test/main.cpp
=> NLP-ENGINE-024 change test to call the taiparse analyzer

lite/parse.cpp
=> NLP-ENGINE-027 ifdef out sql headers

cs/libprim/str.cpp
=> NLP-ENGINE-028 Remove strlen_cmp warning.

include/Api/lite/nlp_engine.h, lite/nlp_engine.cpp, nlplib/nlplib.cpp, nlplib/nlplib.h, test/CMakeLists.txt, test/main2.cpp
Add support for more than one analyzer per row.
Add test2.exe (seg fault)
Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>
=> Allow working directory to be supplied by API

nlplib/nlplib.cpp
Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>
=> NLPLIB Typo in the cleanup code

.vscode/launch.json
=> NLP-ENGINE-030 added launch test for nlp.exe

lite/nlp_engine.cpp
=> NLP-ENGINE-031 if workingFolder is null

include/Api/lite/nlp.h, include/Api/lite/nlp_engine.h, include/Api/lite/vtrun.h, lite/Aseq.cpp, lite/fn.cpp, lite/fnrun.cpp, lite/iaction.cpp, lite/nlp.cpp, lite/nlp_engine.cpp, lite/rug.cpp, lite/vtrun.cpp
=> NLP-ENGINE-030. Remove global VTRun_Ptr. [DEGLOB]

.vscode/launch.json, analyzers/corporate/spec/analyzer.seq, include/Api/lite/nlp_engine.h, lite/nlp_engine.cpp, nlp/main.cpp, test/main.cpp
=> NLP-ENGINE-033 Fixed workspace problem

nlp/main.cpp
=> NLP-ENGINE-036 added directory to the help printout for nlp.exe

nlp/main.cpp
=> NLP-ENGINE-037 typos in nlp.exe --help

visualtext/analyzer/logs/.gitignore, visualtext/analyzer/spec/analyzer.seq
=> NLP-ENGINE-038 Fixing new analyzer template

analyzers/corporate/spec/analyzer.seq, lite/nlp_engine.cpp
=> NLP-ENGINE-039 fixed workspace directory paths

lite/fn.cpp
=> NLP-ENGINE-041 Fixed buffer problem with getstrval

visualtext/spec/KBDump.pat
=> NLP-ENGINE-042 Added KB dump functions to VisualText library functions

visualtext/spec/KBDump.pat, visualtext/spec/KBDumpFuncs.pat
=> NLP-ENGINE-043 Adding a KBDump library pass

visualtext/spec/KBDumpFuncs.pat
=> NLP-ENGINE-044 Add "full" option to KBDump functions

visualtext/spec/KBDumpFuncs.pat
=> NLP-ENGINE-045 Bettering the KB dump function

lite/ana.cpp
=> NLP-ENGINE-040 Skipping folders, stubs, and ends as passes

lite/ana.cpp
=> NLP-ENGINE-047 missing paren

analyzers/noop/spec/stuff.pat, include/Api/lite/nlp.h, include/Api/lite/nlp_engine.h, include/Api/my_tchar.h, lite/nlp.cpp, lite/nlp_engine.cpp, test/main.cpp
=> NLP-ENGINE-034 Analyzer strstream i/o.

visualtext/spec/KBDisplay.pat, visualtext/spec/KBFuncs.pat
=> NLP-ENGINE-050 bettering KB library functions

analyzers/corporate/logs/.gitignore, analyzers/noop/logs/.gitignore, analyzers/taiparse/logs/.gitignore
=> NLP-ENGINE-053 Added empty logs directories to example analyzers

lite/nlp_engine.cpp
=> NLP-ENGINE-054 Fixed path problems for windows and linux

lite/nlp_engine.cpp, nlp/CMakeLists.txt
=> NLP-ENGINE-057 Fix directory permissions and nlp.exe problem

cs/include/consh/arg.h, cs/libconsh/arg.cpp, cs/libconsh/cmd.cpp, cs/libconsh/cmd.h, cs/libconsh/ui.cpp, cs/libprim/list.cpp, include/Api/prim/list.h, lite/nlp_engine.cpp
=> NLP-ENGINE-058 Fixing windows crashes

cs/libconsh/ui.cpp, cs/libprim/list.cpp, cs/libqconsh/arg.cpp, cs/libqconsh/ind.cpp, cs/libqconsh/ui.cpp, include/Api/prim/list.h
=> NLP-ENGINE-061 more "long" fixes

cs/libconsh/arg.cpp, cs/libkbm/attr.cpp, cs/libkbm/con_.cpp, cs/libkbm/dict.cpp
=> NLP-ENGINE-066 fixed more compiler warnings

analyzers/corporate/tmp/README.md, analyzers/noop/tmp/README.md, visualtext/analyzer/tmp/README.md
=> NLP-ENGINE-067 add tmp directories for the function kbdumptree

.vscode/launch.json, include/Api/lite/nlp_engine.h, lite/nlp_engine.cpp
=> NLP-ENGINE-068 Added processing a folder of texts

analyzers/corporate/spec/output.pat
=> NLP-ENGINE-070 Fixed corporate output for regression testing

analyzers/taiparse/spec/buff_out.pat, include/Api/lite/nlp.h, include/Api/lite/nlp_engine.h, include/Api/lite/parse.h, lite/nlp.cpp, lite/nlp_engine.cpp, lite/parse.cpp, lite/post.cpp, test/main.cpp
Signed-off-by: David de Hilster <dehilsterlexis>
=> NLP-ENGINE-072 ostrstream to ostringstream & taiparse output mod

visualtext/spec/KBDisplay.nlp, visualtext/spec/KBFuncs.nlp
=> NLP-ENGINE-075 Fixed DisplayKB function in nlp library functions

include/Api/lite/Arun.h, lite/fn.cpp, lite/fn.h, lite/fnrun.cpp, lite/func_defs.h, lite/funcs.h, lite/str.cpp, lite/str.h
=> NLP-ENGINE-177 Add strstartswith

visualtext/spec/KBFuncs.nlp
=> NLP-ENGINE-178 Pass level to DisplayAttributes function

visualtext/analyzers/english/kb/user/main.kb, visualtext/analyzers/english/kb/user/numbers.kb
=> NLP-ENGINE-180 Add numerics to english dictionary

lite/dicttok.cpp
=> NLP-ENGINE-181 Removed spurious POS attributes

analyzers/parse_en-us/spec/funs.nlp
=> NLP-ENGINE-182 removed stringstartswith since it is now part of NLP++

lite/dicttok.cpp
=> NLP-ENGINE-183 put back in "pos num" in dicttok.

lite/parse.cpp
=> NLP-ENGINE-184 tree files from .log to .tree

include/Api/lite/nlp_engine.h, lite/nlp_engine.cpp
=> NLP-ENGINE-185 change workdir to std::string

lite/nlp_engine.cpp
=> NLP-ENGINE-189 Don't create directories with silent flag

lite/fn.cpp, lite/nlp.cpp, nlp/main.cpp
=> NLP-ENGINE-191 Fixes to memory leaks and initializations

cs/libconsh/cg.cpp, cs/libprim/list.cpp
=> NLP-ENGINE-192 Fix compile errors on Centos and CLang

nlp/main.cpp
=> NLP-ENGINE-203 Update version number for windows

nlp/main.cpp
=> NLP-ENGINE-204 Redo Release Run

.github/workflows/linux-build.yml, .github/workflows/macos-build.yml, .github/workflows/nlpengine.yml, .github/workflows/visualtext.yml, .github/workflows/windows-build.yml
=> NLP-ENGINE-205 zipping nlp.exe and icu dlls

nlp/main.cpp
=> NLP-ENGINE-206 Run new actions

.github/workflows/linux-build-icu.yml, .github/workflows/linux-build.yml, .github/workflows/macos-build-icu.yml, .github/workflows/macos-build.yml, .github/workflows/test-linux.yml, .github/workflows/test-macos.yml, .github/workflows/test-windows.yml, .github/workflows/windows-build-icu.yml, .github/workflows/windows-build.yml, nlp/main.cpp
=> NLP-ENGINE-207 correcting action files

.github/workflows/test-macos.yml, .github/workflows/test-windows.yml, .github/workflows/windows-build.yml, nlp/main.cpp
=> NLP-ENGINE-209 Zip natively

.github/workflows/linux-build.yml, .github/workflows/macos-build.yml, .github/workflows/test-linux.yml, .github/workflows/windows-build.yml, nlp/main.cpp
=> NLP-ENGINE-210 Windows zip on github

.github/workflows/linux-build.yml
=> NLP-ENGINE-211 correction to linux script

.github/workflows/linux-build.yml, .github/workflows/macos-build.yml, nlp/main.cpp
=> NLP-ENGINE-212 fixing yml script errors

.github/workflows/macos-build.yml, .github/workflows/test-linux.yml, .github/workflows/windows-build.yml, nlp/main.cpp
=> NLP-ENGINE-213 yml tweaks

.github/workflows/macos-build.yml, .github/workflows/test-linux.yml, .github/workflows/test-macos.yml, .github/workflows/test-windows.yml, nlp/main.cpp
=> NLP-ENGINE-214 yml tweaks

.github/workflows/test-linux.yml, .github/workflows/test-macos.yml, .github/workflows/test-windows.yml, nlp/main.cpp
=> NLP-ENGINE-215 yml tweaks

lite/str.cpp, nlp/main.cpp
=> NLP-ENGINE-216 fixed strpiece bug

include/Api/lite/Arun.h, include/Api/lite/pn.h, lite/Arun.cpp, lite/dicttok.cpp, lite/dicttok.h, lite/literug.cpp, lite/pat.cpp, lite/pn.cpp, lite/str.cpp, lite/tok.cpp, lite/unicu.cpp, lite/unicu.h, nlp/main.cpp
=> NLP-ENGINE-217 Adding _xEMOJI & Putting ICU into its own namespace

lite/dlist.h, lite/fn.cpp, lite/fnrun.cpp, lite/htab.cpp, lite/nlp.cpp, lite/nlp_engine.cpp
=> NLP-ENGINE-218 Bug fixes from Gavin Halliday

.github/workflows/macos-build.yml, .github/workflows/test-linux.yml, .github/workflows/test-macos.yml, .github/workflows/test-windows.yml, nlp/CMakeLists.txt, nlp/main.cpp
=> NLP-ENGINE-219 add -version test to GitHub actions

.github/workflows/macos-build.yml, nlp/main.cpp
=> VSCODE-NLP-223 mac lib files need "m"

.github/workflows/windows-build.yml, nlp/main.cpp
=> NLP-ENGINE-224 windows-build.yml remove "d" from name

.github/workflows/test-linux.yml, .github/workflows/test-macos.yml, .github/workflows/windows-build.yml, nlp/main.cpp
=> NLP-ENGINE-225 Fix windows build script

nlp/main.cpp
=> NLP-ENGINE-226 remote debug from --version and --help

.github/workflows/linux-build.yml, .github/workflows/macos-build.yml, .github/workflows/test-linux.yml, .github/workflows/test-macos.yml, .github/workflows/test-windows.yml, .github/workflows/windows-build.yml, nlp/main.cpp
=> NLP-ENGINE-227 remove icuind file from the yml scripts

lite/tok.cpp, lite/unicu.cpp, lite/unicu.h, nlp/main.cpp
=> NLP-ENGINE-229 added Nepali tokenization fixes

nlp/main.cpp
Signed-off-by: David de HIlster <david.dehilster@lexisnexisrisk.com>
=> NLP-ENGINE-234 updated version number

nlp/main.cpp
=> NLP-ENGINE-235 Updated the analyzers folder

include/Api/lite/parse.h, include/Api/lite/pn.h, lite/Arun.cpp, lite/cmltok.cpp, lite/cmltok.h, lite/dicttok.cpp, lite/dicttok.h, lite/fn.cpp, lite/fnrun.cpp, lite/parse.cpp, lite/pn.cpp, lite/post.cpp, lite/str.cpp, lite/str.h, lite/tok.cpp, lite/tok.h, nlp/main.cpp
=> NLP-ENGINE-232 Added Unicode start, end to parse tree

nlp/main.cpp
Signed-off-by: David de Hilster <david.dehislter@lexisnexisrisk.com>
=> NLP-ENGINE-237 to force regeneration of assets replaced by hand

nlp/main.cpp, vcpkg.json
Signed-off-by: David de Hilster <david.dehislter@lexisnexisrisk.com>
=> NLP-ENGINE-238 require vcpkg icu version 70 or greater

nlp/main.cpp, vcpkg.json
Signed-off-by: David de Hilster <david.dehislter@lexisnexisrisk.com>
=> NLP-ENGINE-240 version fixing I hope

include/Api/lite/nlp.h, include/Api/lite/nlp_engine.h, lite/nlp.cpp, lite/nlp_engine.cpp, lite/str.cpp, nlp/main.cpp, test/main.cpp
=> NLP-ENGINE-244 upgraded istrstream to istringstream

nlp/main.cpp
=> NLP-ENGINE-246 updated --version output

lite/ana.cpp, lite/dicttok.cpp
=> NLP-ENGINE-250 chartok shouldn't call the dictionary

nlp/main.cpp
=> NLP-ENGINE-251 Forgot to update version number

README.md, nlp/main.cpp
=> NLP-ENGINE-252 Added tutorial links to the README.md

include/Api/lite/rfasem.h, lite/Arun.cpp, lite/fn.cpp, lite/fnrun.cpp, lite/iarg.cpp, lite/iexpr.cpp, lite/rfasem.cpp, nlp/main.cpp
=> NLP-ENGINE-253 change tree concept argument name to concept name

include/Api/lite/htab.h, include/Api/lite/kb.h, include/Api/lite/stab.h, include/Api/lite/sym.h
=> NLP-ENGINE-254 fixed missing headers

.github/workflows/linux-build.yml, .github/workflows/test-linux.yml
=> NLP-ENGINE-254 Update yml scripts move directory listing

lite/str.cpp
=> NLP-ENGINE-255 Changed strlength to be unicode

nlp/main.cpp
=> NLP-ENGINE-256 update version number for nlp.exe

nlp/main.cpp
=> NLP-ENGINE-257 Updating the version number

include/Api/lite/Arun.h, lite/fn.cpp, lite/fn.h, lite/fnrun.cpp, lite/func_defs.h, lite/funcs.h
=> NLP-ENGINE-260 Added writedb function to NLP++

nlp/main.cpp
=> NLP-ENGINE-276 updated version number

.github/workflows/macos-build.yml, nlp/main.cpp
=> NLP-ENGINE-277 path change in macos-build.yml for icu

cs/libprim/unicu.cpp, include/Api/prim/unicu.h, lite/tok.cpp, nlp/main.cpp
=> NLP-ENGINE-279 Adding emoji variations and another emoji range

include/Api/lite/nlp.h, lite/ivar.cpp, lite/nlp.cpp, lite/nlp_engine.cpp, nlp/main.cpp
=> NLP-ENGINE-281 Added $isfirstfile global variable

cs/libprim/unicu.cpp, include/Api/prim/unicu.h, lite/fn.cpp, lite/fnrun.cpp, nlp/main.cpp
=> NLP-ENGINE-282 unicode for strcontains && strcontainsnocase

include/Api/lite/nlp.h, include/Api/lite/parse.h, lite/io.cpp, lite/io.h, lite/ivar.cpp, lite/nlp.cpp, lite/nlp_engine.cpp, lite/parse.cpp, nlp/main.cpp
=> NLP-ENGINE-283 Added global $isdirrun and $inputparent

include/Api/lite/ana.h, include/Api/lite/parse.h, lite/ana.cpp, lite/ivar.cpp, lite/nlp.cpp, lite/parse.cpp, nlp/main.cpp
=> NLP-ENGINE-284 added $kbpath

cs/libconsh/cg.cpp, include/Api/consh/cg.h, lite/dicttok.cpp, nlp/main.cpp
=> NLP-ENGINE-285 Added reading all.dict file for dictionary lookup

cs/libconsh/cg.cpp, include/Api/consh/cg.h, lite/dicttok.cpp, nlp/main.cpp
=> NLP-ENGINE-287 Dict files allow quoted values, open all.dict once

cs/libconsh/cg.cpp, include/Api/consh/cg.h, nlp/main.cpp
=> NLP-ENGINE-288 add dictfile flag

cs/libconsh/cg.cpp, include/Api/consh/cg.h, lite/dicttok.cpp, lite/parse.cpp, nlp/main.cpp
=> NLP-ENGINE-288 entire all.dict is read into memory much faster

nlp/main.cpp
=> NLP-ENGINE-291 Forgot to update version number

nlp/main.cpp
=> NLP-ENGINE-293 updated version number

cs/libconsh/cg.cpp, nlp/main.cpp
=> NLP-ENGINE-294 Reads in more than one word per line from dict files

nlp/main.cpp
=> NLP-ENGINE-294 update version

.github/workflows/linux-build.yml, .github/workflows/macos-build.yml, .github/workflows/windows-build.yml, nlp/main.cpp
=> NLP-ENGINE-296 Update yml scripts to trigger

.github/workflows/nlpengine.yml, .github/workflows/visualtext.yml, nlp/main.cpp
=> NLP-ENGINE-297 updated to yml files visualtext.yml and nlpengine.yml

.github/workflows/build-enginefiles.yml, .github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-visualfiles.yml, .github/workflows/build-windows.yml
=> NLP-ENGINE-299 Updating to test action scripts

nlp/main.cpp
=> NLP-ENGINE-300 Test new action scripts

.github/workflows/build-enginefiles.yml, .github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-visualfiles.yml, .github/workflows/build-windows.yml, .github/workflows/move-assets.yml
=> NLP-ENGINE-302 More script changes

.github/workflows/move-assets.yml
=> NLP-ENGINE-303 Changed action in move assets

.github/workflows/move-assets.yml
=> NLP-ENGINE-304 added zip files to move-assets.yml

.github/workflows/build-windows.yml
=> NLP-ENGINE-305 fixing bug in build-windows.yml

.github/workflows/build-linux.yml, .github/workflows/build-macos.yml
=> NLP-ENGINE-306 typos in some scripts

.github/workflows/move-assets.yml
=> NLP-ENGINE-307 one more fix to move-assets.yml

.github/workflows/move-assets.yml
=> NLP-ENGINE-308 Add assets to release in move-assets.yml

.github/workflows/move-assets.yml
=> NLP-ENGINE-312 more fixes to move-assets.yml

.github/workflows/move-assets.yml
=> NLP-ENGINE-313 added needs to move-assets.yml

.github/workflows/move-assets.yml
=> NLP-ENGINE-314 fix in move-assets.yml

.github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-windows.yml
=> NLP-ENGINE-317 more and more

.github/workflows/move-assets.yml
=> NLP-ENGINE-318 More tries with move-assets.yml

.github/workflows/build-enginefiles.yml, .github/workflows/build-linux.yml, .github/workflows/build-visualfiles.yml, .github/workflows/build-windows.yml, .github/workflows/move-assets.yml
=> NLP-ENGINE-319 fixes

.github/workflows/build-enginefiles.yml, .github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-visualfiles.yml, .github/workflows/build-windows.yml, .github/workflows/move-assets.yml
=> NLP-ENGINE-320 Changes

.github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-windows.yml, .github/workflows/move-assets.yml
=> NLP-ENGINE-322 updates

.github/workflows/build-enginefiles.yml, nlp/main.cpp
=> NLP-ENGINE-329 Remove analyzer submodule, now uploaded separately

.github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-windows.yml, .github/workflows/move-assets.yml, nlp/main.cpp
=> NLP-ENGINE-332 Making sure dlls are not renamed

.github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-windows.yml, .github/workflows/move-assets.yml, CMakeLists.txt, cs/libconsh/cg.cpp, include/Api/consh/cg.h, include/Api/lite/dir.h, include/Api/lite/nlp_engine.h, lite/CMakeLists.txt, lite/dir.cpp, lite/nlp_engine.cpp, nlp/CMakeLists.txt, nlp/main.cpp, vcpkg.json
=> NLP-ENGINE-334 Remove boost and use std::filesystem and std::regex

cs/libconsh/cg.cpp, include/Api/consh/cg.h, nlp/main.cpp
=> NLP-ENGINE-335 Adding openKBB

cs/libconsh/cg.cpp, nlp/main.cpp
=> NLP-ENGINE-336 Added comments to .dict and .kbb files

include/Api/lite/ana.h, include/Api/lite/parse.h, lite/ana.cpp, lite/ivar.cpp, lite/nlp.cpp, lite/parse.cpp, nlp/main.cpp
=> NLP-ENGINE-337 added global $anaspath

cs/libconsh/cg.cpp, cs/libprim/unicu.cpp, include/Api/prim/unicu.h, lite/dicttok.cpp, lite/dicttok.h
=> NLP-ENGINE-339 Adding phrases to dictionary

nlp/main.cpp
=> NLP-ENGINE-340 Update version number in main.cpp

cs/libconsh/cg.cpp, nlp/main.cpp
=> NLP-ENGINE-342 readDict double quote bug fixed

lite/dicttok.cpp, nlp/main.cpp
=> NLP-ENGINE-345 restored lower, cap, and upper to dicktok

lite/dicttok.cpp, nlp/main.cpp
=> NLP-ENGINE-346 fixed suggested node name length problem

lite/dicttok.cpp, nlp/main.cpp
=> NLP-ENGINE-347 text for phrases bug fix

cs/libconsh/cg.cpp, nlp/main.cpp
=> NLP-ENGINE-348 Double quotes allowed for KBB concepts

lite/dir.cpp, nlp/main.cpp
=> NLP-ENGINE-349 Fixed logic problem with processing a directory

nlp/main.cpp
=> NLP-ENGINE-350 Forgot to save some files for last fix

cs/libconsh/cg.cpp, nlp/main.cpp
=> NLP-ENGINE-351 Fixing readKBB

cs/libconsh/cg.cpp, nlp/main.cpp
=> NLP-ENGINE-352 more fixes to readKBB

.github/workflows/build-windows.yml, cs/libconsh/cg.cpp, lite/dicttok.cpp, nlp/main.cpp
=> NLP-ENGINE-353 Fixes to parsing KBB files

cs/libconsh/cg.cpp, nlp/main.cpp
=> NLP-ENGINE-356 con type was wrong in attrValType

include/Api/lite/Arun.h, lite/fn.cpp, lite/fn.h, lite/fnrun.cpp, lite/func_defs.h, lite/funcs.h, nlp/main.cpp
=> NLP-ENGINE-357 added getfltval

cs/libconsh/cg.cpp, nlp/main.cpp
=> NLP-ENGINE-358 Fixing readKBB

lite/nlp_engine.cpp, nlp/main.cpp
=> NLP-ENGINE-359 isdirrun bug fix

lite/Arun.cpp, lite/pat.cpp, nlp/main.cpp
=> NLP-ENGINE-361 changing alphabetic to == PNALPHA in pat.cpp

data/rfb/spec/bigtok.nlp, nlp/main.cpp
=> NLP-ENGINE-364 edited rfb grammar to allow _😀

cs/libconsh/cg.cpp, cs/libkbm/attr.cpp, include/Api/consh/cg.h, include/Api/kbm/Akbm.h, lite/dicttok.cpp, nlp/main.cpp
=> NLP-ENGINE-366 Fixed two dict file problems in reading and matching

lite/dicttok.cpp, nlp/main.cpp
=> NLP-ENGINE-368 fixing dictionary phrases and singles

lite/fn.cpp, lite/pre.cpp, nlp/main.cpp
=> NLP-ENGINE-369 converting some str lengths to unicode
